name: Script Workflow

on:
  workflow_dispatch:

jobs:
  script-workflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Script Workflow Job
        run: |
          echo "Hello Script Workflow!"

      - name: Run Python Script
        run: python script.py
