name: Cron Workflow

on:
  schedule:
    # - cron: "*/5 * * * *" # runs in every 5 minutes
    - cron: "0 0 * * *"  # runs once a day at midnight UTC

jobs:
  cron-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Cron Workflow
        run: |
          echo "Hello Cron Job!"
