name: Multi Jobs Workflow

on:
  push:
    branches:
      - main

jobs:
  first-workflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: |
          echo "Hello First Workflow!"

  second-workflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: |
          echo "Hello second Workflow!"