name: Conditional Workflow

on:
  push:
    paths:
      - 'backend/**'

jobs:
  conditional-workflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: Conditional Workflow Job
        run: |
          echo "Buiulding Backend Images!"