# matrix is a way to run the same job multiple 
# times with different inputs
name: Simple Matrix Workflow

on:
  workflow_dispatch: # Trigger this workflow manually

jobs:
  matrix-workflow-job:
    runs-on: ubuntu-latest # Runner environment is Ubuntu

    strategy:
      matrix:
        fruit: [apple, banana] # Test for two different fruits
        color: [red, yellow] # Test for two different colors

    steps:
      - name: Print Fruit and Color
        run: |
          echo "Fruit: ${{ matrix.fruit }}"
          echo "Color: ${{ matrix.color }}"
          echo "Fruit and Color: ${{ matrix.fruit }} and ${{ matrix.color }}"
