# matrix is a way to run the same job multiple 
# times with different inputs
name: Node.js and OS Matrix Workflow

on:
  workflow_dispatch:  # Trigger this workflow manually

jobs:
  matrix-workflow-job:
    runs-on: ubuntu-latest  # The base runner is Ubuntu

    strategy:
      matrix:
        node-version: [14, 16]  # Test for Node.js versions 14 and 16
        os: [ubuntu-latest, windows-latest]  # Test on Ubuntu and Windows

    steps:
      - name: Set up Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install  # Install dependencies using npm

      - name: Run tests
        run: npm test  # Run the tests
